"""
Project-wide default constants.

If a value should be configurable by the user, it should also be duplicated
or overridden in configs/*.yaml.
"""

# Supported platform names (as returned by platform.system())
PLATFORM_WINDOWS = "Windows"
PLATFORM_MACOS = "Darwin"
PLATFORM_LINUX = "Linux"

# Camera defaults
DEFAULT_CAMERA_ID = 0
DEFAULT_FRAME_WIDTH = 1280
DEFAULT_FRAME_HEIGHT = 720
DEFAULT_FPS = 30
DEFAULT_MIRROR_FRAME = True
DEFAULT_CAMERA_FOURCC = "AUTO"
LINUX_DEFAULT_CAMERA_FOURCC = "MJPG"
MINIMUM_TARGET_FPS = 15.0
# Capture frames on a background thread so camera I/O and MJPG decoding overlap
# with MediaPipe inference instead of serializing with it.
DEFAULT_CAMERA_THREADED = True

# MediaPipe / hand landmarks
DEFAULT_LANDMARK_COUNT = 21
DEFAULT_LANDMARK_DIMENSIONS = 3
DEFAULT_MAX_HANDS = 1
DEFAULT_MODEL_COMPLEXITY = 1
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.65
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.65
DEFAULT_MEDIAPIPE_MODEL_PATH = "assets/models/mediapipe/hand_landmarker.task"
DEFAULT_MEDIAPIPE_INPUT_WIDTH = 640
DEFAULT_MEDIAPIPE_INPUT_HEIGHT = 360

# Gesture recognition thresholds
DEFAULT_STATIC_CONFIDENCE_THRESHOLD = 0.50
DEFAULT_DYNAMIC_CONFIDENCE_THRESHOLD = 0.75

# Static gesture smoothing
DEFAULT_STATIC_SMOOTHING_WINDOW = 5

# Dynamic gesture sequence
DEFAULT_SEQUENCE_LENGTH = 40

# Cursor control
DEFAULT_CURSOR_ENABLED = False
DEFAULT_POINTER_LANDMARK = "INDEX_MCP"
DEFAULT_CURSOR_SMOOTHING_ALPHA = 1.0
DEFAULT_CURSOR_DRY_RUN = True
DEFAULT_CURSOR_MARGIN_X = 0.08
DEFAULT_CURSOR_MARGIN_TOP = 0.10
DEFAULT_CURSOR_MARGIN_BOTTOM = 0.12
DEFAULT_CURSOR_INVERT_Y = False
DEFAULT_CURSOR_MIN_CUTOFF = 7.0
DEFAULT_CURSOR_BETA = 0.080
DEFAULT_CURSOR_DERIVATIVE_CUTOFF = 1.0
DEFAULT_CURSOR_DEAD_ZONE_POINTS = 0.0
DEFAULT_CURSOR_MAX_SPEED_POINTS_PER_SECOND = 50000.0
DEFAULT_CURSOR_REACQUIRE_FRAMES = 1
DEFAULT_CURSOR_LOST_RESET_SECONDS = 0.20
DEFAULT_STRICT_SCREEN_BOUNDS = False

# Cursor gesture recognition
DEFAULT_CURSOR_GESTURE_CONFIDENCE = 1.0
DEFAULT_INDEX_PINCH_TRACKING_ENABLED = True
DEFAULT_INDEX_PINCH_THUMB_TIP = 4
DEFAULT_INDEX_PINCH_TIP = 8
DEFAULT_INDEX_SQUEEZE_RATIO = 0.10
DEFAULT_INDEX_RELEASE_RATIO = 0.14
DEFAULT_MIDDLE_PINCH_TRACKING_ENABLED = True
DEFAULT_MIDDLE_PINCH_THUMB_TIP = 4
DEFAULT_MIDDLE_PINCH_TIP = 12
DEFAULT_MIDDLE_PINCH_PRESS_RATIO = 0.10
DEFAULT_MIDDLE_PINCH_RELEASE_RATIO = 0.14

# Mouse / cursor action safety
DEFAULT_MOUSE_ACTION_COOLDOWN_SECONDS = 0.50

# Runtime
DEFAULT_DEBUG_MODE = True
DEFAULT_SAFE_EXIT_KEY = "q"
DEFAULT_WINDOW_NAME = "Oil Gestures"
# Downscale the preview window before drawing/imshow; the high-resolution capture
# is still fed to MediaPipe. 0 keeps the full camera frame. Large preview blits
# (especially via the Qt HighGUI backend under XWayland) dominate the frame
# budget, so a smaller preview is the biggest single FPS win on Linux.
DEFAULT_PREVIEW_WIDTH = 960
DEFAULT_SHOW_CAMERA_FEED = True
DEFAULT_SHOW_LANDMARKS = True
DEFAULT_SHOW_DEBUG_OVERLAY = True
FPS_METER_SAMPLE_INTERVAL_SECONDS = 0.5
FPS_METER_SMOOTHING_ALPHA = 0.25
PERFORMANCE_LOG_INTERVAL_SECONDS = 5.0
PERFORMANCE_TIMING_SMOOTHING_ALPHA = 0.15
OPENCV_ESCAPE_KEY_CODE = 27
PAUSE_KEY_CHARACTERS = (" ", "p")
MOUSE_TEST_TARGETS = ((0.50, 0.50), (0.60, 0.50), (0.50, 0.60), (0.50, 0.50))
MOUSE_TEST_STEP_SECONDS = 0.2

# Logging
DEFAULT_LOGGER_NAME = "oil_gestures"
